# Generated by Django 4.1.1 on 2022-09-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_rooms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='projector',
            field=models.BooleanField(),
        ),
    ]
