# Generated by Django 4.1.1 on 2022-09-15 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_rooms_app', '0002_alter_room_projector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserwvtion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('comment', models.CharField(max_length=128)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_rooms_app.room')),
            ],
            options={
                'unique_together': {('date', 'comment')},
            },
        ),
    ]
