# Generated by Django 4.1.1 on 2022-09-17 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_rooms_app', '0005_alter_reservation_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
    ]
