# Generated by Django 4.1.1 on 2022-09-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_rooms_app', '0006_alter_reservation_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='room',
            new_name='room_id',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='comment',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='projector',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='seats',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('date', 'room_id')},
        ),
    ]
