# Generated by Django 4.1.1 on 2022-09-17 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_rooms_app', '0007_rename_room_reservation_room_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='room_id',
            new_name='room',
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('date', 'room')},
        ),
    ]
