# Generated by Django 4.1.3 on 2022-11-06 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_rooms_app', '0010_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='room',
        ),
    ]
